//
//  CloudyRecFstore.h
//  Generated by CloudyRec - mobile backend platform.
//  Copyright (c) 2012 Rival Edge Pte Ltd. All rights reserved.
//

#import "CloudyRecResource.h"
#import "SimpleHttpResponse.h"


@interface CloudyRecFstore : CloudyRecResource
-(void)uploadWithData:(NSData*)data FileName:(NSString*)filename ContentType:(NSString*)contentType ID:(NSString*)_id onCompletion:(httpResponseBlock)completion OnFailer:(httpErrorBlock)fail;
-(void)listWithCompletion:(cloudyRecRespondBlock)completion OnFailer:(httpErrorBlock)fail;
-(void)listWithQuery:(NSString*)query Limit:(int)limit Page:(int)page onCompletion:(cloudyRecRespondBlock)completion OnFailer:(httpErrorBlock)fail;
-(void)setTagWithID:(NSString*)tagID Tags:(NSArray*)tagsList onCompletion:(cloudyRecRespondStirngBlock)completion OnFailer:(httpErrorBlock)fail;
-(void)getTagWithID:(NSString*)tagID onCompletion:(cloudyRecRespondBlock)completion onFailer:(httpErrorBlock)fail;
-(void)deleteTagWithID:(NSString*)tagID onCompletion:(cloudyRecRespondBoolBlock)completion onFailer:(httpErrorBlock)fail;
-(void)downloadWithID:(NSString*)tagID onCompletion:(cloudyRecRespondDataBlock)completion onFailer:(httpErrorBlock)fail;
//public String setTags(String id, ArrayList<String> tags)
@end
