//
//  Exercise.m
//  Generated by CloudyRec - mobile backend platform.
//  Copyright (c) 2012 Rival Edge Pte Ltd. All rights reserved.
//

#import "Exercise.h"
@interface Exercise()
@end
@implementation Exercise 
@synthesize exerciseResKey;
@synthesize distance;
@synthesize points;
@synthesize time;
@synthesize frienduser;
@synthesize type;

-(id)initWithExerciseDistance:(NSString*)distance_ Points:(NSString*)points_ Time:(NSDate*)time_ Frienduser:(NSString*)frienduser_ Type:(int)type_{

  if(self=[super init]) {
	    distance=[distance_ copy];
	    points=[points_ copy];
	    time=[time_ copy];
	    frienduser=[frienduser_ copy];
	    type=type_;
    exerciseResKey=@"6BENgryQ7v";
  }
  return self;
}

-(void)dealloc {
  [exerciseResKey release];
  [distance release];
  [points release];
  [time release];
  [frienduser release];
  [super dealloc];
}

-(id)init {
  if(self=[super init]) {
	self.exerciseResKey=@"6BENgryQ7v";
  }
  return self;
}


-(NSString*)getId {
  return self._id;
}

-(NSString*)getResourceKey {
return exerciseResKey;
}

-(void)load:(NSString*)id_ onComplete:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail{
   [self loadFromCloud:id_ onComplete:^(NSDictionary* data){
    NSDictionary* dict=[NSDictionary dictionaryWithDictionary:data];
    if(dict!=nil) {
      [self setData:dict];
      completion(YES);
    }
    else {
      completion(NO);
    }
  }onFailure:^(NSError* error){
    fail(error);
  }];
}

-(void) list:(NSString*)query onComplete:(cloudyRecRespondBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail {
  [self list:query Limit:10 Page:1 onComplete:completion onFailure:fail];
}

-(void) list:(NSString*)query Limit:(int)limit Page:(int)page onComplete:(cloudyRecRespondBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail {
  
  [self listFromCloud:query Limit:limit Page:page onComplete:^(NSArray* complete){
    NSArray* ja;
    NSMutableArray* resources = [[NSMutableArray alloc] init];
    ja =[[NSArray alloc] initWithArray:complete];
    for (NSDictionary* obj in ja) {
      Exercise* res =[[Exercise alloc] init];
      [res setData:obj];
      [resources addObject:res];
      [res release];
    }
    [ja release];
    completion([resources autorelease]);
  }onFailure:^(NSError* error){
    
    fail(error);
  }];

}


-(void)saveWithCompletion:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail {
  NSMutableDictionary* data = [[NSMutableDictionary alloc] init];
	//date format
	NSDateFormatter *df = [[NSDateFormatter alloc] init];
	[df setLocale:[[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"] autorelease]];
	NSTimeZone *timeZone = [NSTimeZone timeZoneWithName:@"UTC"];
	[df setTimeZone:timeZone];
	[df setDateFormat:@"yyyy-MM-dd'T'HH:mm:ss"];
  [data setValue:self.distance forKey:@"distance"];
  [data setValue:self.points forKey:@"points"];
	  NSString* tmp_date_time=[df stringFromDate:self.time];
	  [data setValue:tmp_date_time forKey:@"time"];
  [data setValue:self.frienduser forKey:@"frienduser"];
	  [data setValue:[NSNumber numberWithInteger:self.type] forKey:@"type"];

  [df release];
  if(self._id==nil)
  {
    //self._id=[self insertToCloud:data];
    [self insertToCloud:data onComplete:^(NSString* respond){
      self._id = respond;
      
      if(self._id==nil)
      {
        completion(NO);
      }
      else {
          completion(YES);
      }
    }onFailure:^(NSError* err){
      fail(err);
    }];
  }
  else {
    [self updateToCloud:data onComplete:^(NSString* respond){
      self._id = respond;
      
      if(self._id==nil)
      {
        completion(NO);
      }
      else {
        completion(YES);
      }
      
    }onFailure:^(NSError *error){
      fail(error);
    }];
  }
  [data release];
}

-(void)deleteWithCompletion:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail {
  
  if(self._id==nil)
  {
    completion(NO);
  }
  [self deleteFromCloudWithonComplete:^(BOOL respond){
    if(respond) {
      self._id=nil;
    }
    
    completion(respond);
  }onFailure:^(NSError* err){
    fail(err);
  }];
  
}

-(void)setData:(NSDictionary*)data {
  self._id=[data objectForKey:@"id"];

	//date format
	NSDateFormatter *df = [[NSDateFormatter alloc] init];
	[df setLocale:[[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"] autorelease]];
	NSTimeZone *timeZone = [NSTimeZone timeZoneWithName:@"UTC"];
	[df setTimeZone:timeZone];
	[df setDateFormat:@"yyyy-MM-dd'T'HH:mm:ss"];
	  self.distance=[data objectForKey:@"distance"];
	  self.points=[data objectForKey:@"points"];
  NSString* date_str_time=[data objectForKey:@"time"];
  self.time=[df dateFromString:date_str_time];

	  self.frienduser=[data objectForKey:@"frienduser"];
	  self.type=[[data objectForKey:@"type"] intValue];
        [df release];
}
@end
