//
//  Quiz.h
//  Generated by CloudyRec - mobile backend platform.
//  Copyright (c) 2012 Rival Edge Pte Ltd. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "CloudyRecResource.h"
@interface Quiz : CloudyRecResource
{
  @private
  NSString* quizResKey;
  int score;
  NSString* points;
  NSDate* time;

}

@property(nonatomic,retain) NSString *quizResKey;
@property(nonatomic,assign) int score;
@property(nonatomic,retain) NSString *points;
@property(nonatomic,retain) NSDate *time;


-(id)initWithQuizScore:(int)score_ Points:(NSString*)points_ Time:(NSDate*)time_;

-(id)init;
-(NSString*)getId;
-(NSString*)getResourceKey;
-(void)setData:(NSDictionary*)data;

-(void)load:(NSString*)id_ onComplete:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;
-(void) list:(NSString*)query onComplete:(cloudyRecRespondBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;
-(void) list:(NSString*)query Limit:(int)limit Page:(int)page onComplete:(cloudyRecRespondBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;

-(void)saveWithCompletion:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;
-(void)deleteWithCompletion:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;
@end
