//
//  SimpleHttpResponse.m
//  Generated by CloudyRec - mobile backend platform.
//  Copyright (c) 2012 Rival Edge Pte Ltd. All rights reserved.
//

#import "SimpleHttpResponse.h"

@implementation SimpleHttpResponse
@synthesize body;
@synthesize status;
@synthesize rawData;

@end
