//
//  SimpleHttpResponse.h
//  Generated by CloudyRec - mobile backend platform.
//  Copyright (c) 2012 Rival Edge Pte Ltd. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface SimpleHttpResponse : NSObject
@property(nonatomic,retain) NSString* body;
@property(nonatomic,retain) NSData* rawData;
@property(nonatomic,assign) int status;
@end
