//
//  User.h
//  Generated by CloudyRec - mobile backend platform.
//  Copyright (c) 2012 Rival Edge Pte Ltd. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "CloudyRecResource.h"
@interface User : CloudyRecResource
{
  @private
  NSString* userResKey;
  NSString* username;
  NSString* password;
  int points;

}

@property(nonatomic,retain) NSString *userResKey;
@property(nonatomic,retain) NSString *username;
@property(nonatomic,retain) NSString *password;
@property(nonatomic,assign) int points;


-(id)initWithUserUsername:(NSString*)username_ Password:(NSString*)password_ Points:(int)points_;

-(id)init;
-(NSString*)getId;
-(NSString*)getResourceKey;
-(void)setData:(NSDictionary*)data;

-(void)load:(NSString*)id_ onComplete:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;
-(void) list:(NSString*)query onComplete:(cloudyRecRespondBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;
-(void) list:(NSString*)query Limit:(int)limit Page:(int)page onComplete:(cloudyRecRespondBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;

-(void)saveWithCompletion:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;
-(void)deleteWithCompletion:(cloudyRecRespondBoolBlock)completion onFailure:(cloudyRecRespondErrorBlock)fail;
@end
